version: '3.8'

services:
#  cassandra:
#    image: cassandra:latest
#    container_name: cassandra_container
#    ports:
#      - "9042:9042"
#    environment:
#      - CASSANDRA_CLUSTER_NAME=my_cassandra_cluster
#      - CASSANDRA_SEEDS=cassandra
#      - CASSANDRA_DC=dc1
#      - CASSANDRA_RACK=rack1
#      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
#    volumes:
#      - cassandra_data:/var/lib/cassandra

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_URL=redis://redis_container:6379/

volumes:
  redis_data:
#  cassandra_data: